module.exports = {
    student: getStudent()
};

function getStudent() {
    return [{
        id: 0,
        firstName: 'Alex',
        lastName: 'Pantzialas',
        userName: 'AlexP',
        password: 'truck4',
        readingLevel: 'B',
        isSelected: false
    }, {
        id: 1,
        firstName: 'Manit',
        lastName: 'Banker',
        userName: 'mBanker',
        password: 'cartOne',
        readingLevel: 'A',
        isSelected: false
    }, {
        id: 2,
        firstName: 'DJ',
        lastName: 'Bravo',
        userName: 'djChen',
        password: 'gameOne',
        readingLevel: 'C',
        isSelected: false
    }, {
        id: 3,
        firstName: 'Carl',
        lastName: 'Taylor',
        userName: 'cTyler',
        password: 'apexOne',
        readingLevel: 'B',
        isSelected: false
    }, {
        id: 4,
        firstName: 'Munish',
        lastName: 'Kumar',
        userName: 'mKumar',
        password: 'cpmjOne',
        readingLevel: 'B',
        isSelected: false
    }, {
        id: 5,
        firstName: 'Flat',
        lastName: 'Iron',
        userName: 'iornMan',
        password: 'wordPass',
        readingLevel: 'A',
        isSelected: false
    }, {
        id: 6,
        firstName: 'Sujith',
        lastName: 'Maddi',
        userName: 'smaddi',
        password: 'paychex9',
        readingLevel: 'A',
        isSelected: false
    }, {
        id: 7,
        firstName: 'Vamsi',
        lastName: 'Lolla',
        userName: 'VamsiL',
        password: 'rabbit6',
        readingLevel: 'B',
        isSelected: false
    }, {
        id: 8,
        firstName: 'Rahul',
        lastName: 'Patel',
        userName: 'RahulP',
        password: 'food9',
        readingLevel: 'C',
        isSelected: false
    }, {
        id: 9,
        firstName: 'Ryan',
        lastName: 'Hine',
        userName: 'RyanH',
        password: 'ball3',
        readingLevel: 'B',
        isSelected: false
    }, {
        id: 10,
        firstName: 'Shaun',
        lastName: 'Wright',
        userName: 'ShaunW',
        password: 'yarn2',
        readingLevel: 'C',
        isSelected: false
    }, {
        id: 11,
        firstName: 'Vishy',
        lastName: 'Ganesh',
        userName: 'VishyG',
        password: 'guruChex',
        readingLevel: 'A',
        isSelected: false
    }, {
        id: 12,
        firstName: 'Karen',
        lastName: 'Slazak',
        userName: 'KarenS',
        password: 'cat3',
        readingLevel: 'D',
        isSelected: false
    }, {
        id: 13,
        firstName: 'Pawan',
        lastName: 'Negie',
        userName: 'PawanN',
        password: 'owl8',
        readingLevel: 'A',
        isSelected: false
    }, {
        id: 14,
        firstName: 'Raoni',
        lastName: 'Boaventura',
        userName: 'rBoava',
        password: 'rubyRails',
        readingLevel: 'C',
        isSelected: false
    }, {
        id: 15,
        firstName: 'Sarena',
        lastName: 'Williams',
        userName: 'sWilliams',
        password: 'tenis',
        readingLevel: 'B',
        isSelected: false
    }];
}
